;;; kaocha-runner-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from kaocha-runner.el

(autoload 'kaocha-runner-hide-windows "kaocha-runner" "\
Hide all windows that kaocha has opened." t)
(autoload 'kaocha-runner-run-tests "kaocha-runner" "\
Run tests in the current namespace.
If prefix argument TEST-ID? is present ask user for a test-id to run.

(fn &optional TEST-ID?)" t)
(autoload 'kaocha-runner-run-test-at-point "kaocha-runner" "\
Run the test at point in the current namespace." t)
(autoload 'kaocha-runner-run-all-tests "kaocha-runner" "\
Run all tests." t)
(autoload 'kaocha-runner-show-warnings "kaocha-runner" "\
Display warnings from the last kaocha test run.
Prefix argument SWITCH-TO-BUFFER? opens a separate window.

(fn &optional SWITCH-TO-BUFFER?)" t)
(register-definition-prefixes "kaocha-runner" '("kaocha-runner-"))

;;; End of scraped data

(provide 'kaocha-runner-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; kaocha-runner-autoloads.el ends here
