#!/usr/bin/env sh
# The above shebang is just to get editors to use an appropriate mode.

# Load scripting addition. See https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa


# Disable window management.
yabai -m config layout float

# Enable window borders

## Recent yabai no longer supports boders

# yabai -m config window_border on
# yabai -m config window_border_width 6
# yabai -m config active_window_border_color 0xFF0000FF   # - was 0XFF50FA7B
# yabai -m config normal_window_border_color 0x00112233 # transparent - was 0xFFBD93F9

## Use JankyBorders instead

# borders active_color=0xff0000ff inactive_color=0x00112233 width=10.0
borders active_color=0xff0000ff inactive_color=0xff494d64 width=10.0
