;;; adoc-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from adoc-asciidoctor.el

(autoload 'adoc-export-html "adoc-asciidoctor" "\
Export the current AsciiDoc buffer to HTML5." t)
(autoload 'adoc-export-docbook "adoc-asciidoctor" "\
Export the current AsciiDoc buffer to DocBook 5." t)
(autoload 'adoc-export-pdf "adoc-asciidoctor" "\
Export the current AsciiDoc buffer to PDF.
Requires the `asciidoctor-pdf' converter to be installed." t)
(autoload 'adoc-export-epub "adoc-asciidoctor" "\
Export the current AsciiDoc buffer to EPUB3.
Requires the `asciidoctor-epub3' converter to be installed." t)
(autoload 'adoc-preview "adoc-asciidoctor" "\
Render the current AsciiDoc buffer and show it in a preview pane." t)
(autoload 'adoc-live-preview-mode "adoc-asciidoctor" "\
Re-render the AsciiDoc preview whenever the buffer is saved.

This is a minor mode.  If called interactively, toggle the
`Adoc-Live-Preview mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `adoc-live-preview-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
 (autoload 'adoc-asciidoctor-menu "adoc-asciidoctor" nil t)
(register-definition-prefixes "adoc-asciidoctor" '("adoc-"))


;;; Generated autoloads from adoc-mode.el

(autoload 'adoc-mode "adoc-mode" "\
Major mode for editing AsciiDoc text files.
Turning on Adoc mode runs the normal hook `adoc-mode-hook'.

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.a\\(?:scii\\)?doc\\'" . adoc-mode))
(register-definition-prefixes "adoc-mode" '("adoc-"))


;;; Generated autoloads from adoc-mode-image.el

(register-definition-prefixes "adoc-mode-image" '("adoc-"))


;;; Generated autoloads from adoc-mode-tempo.el

(register-definition-prefixes "adoc-mode-tempo" '("adoc-temp"))

;;; End of scraped data

(provide 'adoc-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; adoc-mode-autoloads.el ends here
