;;; flycheck-projectile-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flycheck-projectile.el

(autoload 'flycheck-projectile-list-errors "flycheck-projectile" "\
Show a list of all the errors in the current project.
Start the project search at DIR. Efficiently handle the case of
the project not changing since the last time this function was
called.

(fn &optional DIR)" t)
(register-definition-prefixes "flycheck-projectile" '("flycheck-projectile-"))

;;; End of scraped data

(provide 'flycheck-projectile-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flycheck-projectile-autoloads.el ends here
