;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        delete-indentation
        down-list
        forward-sexp
        kill-region
        paredit-backward-up
        ))

(setq mc/cmds-to-run-once
      '(
        ))
