;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        delete-indentation
        down-list
        forward-sexp
        kill-region
        mark-sexp
        markdown-exdent-or-delete
        nomis-meta-w
        nomis-prog-indent-sexp--top-level
        org-beginning-of-line
        org-self-insert-command
        paredit-backslash
        paredit-backward-up
        paredit-doublequote
        paredit-forward-delete
        paredit-forward-down
        paredit-forward-slurp-sexp
        paredit-open-round
        paredit-raise-sexp
        paredit-semicolon
        wdired-finish-edit
        ))

(setq mc/cmds-to-run-once
      '(
        ))
