;;; loccur-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from loccur.el

(autoload 'loccur-current "loccur" "\
Call `loccur' for the current word." t)
(autoload 'loccur "loccur" "\
Perform a simple grep in current buffer.

This command hides all lines from the current buffer except those
containing the regular expression REGEX.  A second call of the function
unhides lines again.

When called interactively, either prompts the user for REGEXP or,
when called with an active region, uses the content of the
region, unless called with the universal prefix (C-u)

(fn REGEX)" t)
(autoload 'loccur-isearch "loccur" "\
Incrementally filter buffer lines.

Like Isearch, but hide buffer lines not matching the search
string.  If Isearch is already active, toggle filtering on or
off.

MODE only has effect if called from outside Isearch, and has the
same meaning as `search-default-mode'.  Interactively, that
default value is used.

(fn &optional MODE)" t)
(register-definition-prefixes "loccur" '("loccur-"))

;;; End of scraped data

(provide 'loccur-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; loccur-autoloads.el ends here
