;;; zenburn-theme-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from zenburn-theme.el

(defvar zenburn-override-colors-alist 'nil "\
Place to override default theme colors.

You can override a subset of the theme's default colors by
defining them in this alist.")
(custom-autoload 'zenburn-override-colors-alist "zenburn-theme" t)
(defvar zenburn-override-semantic-colors-alist 'nil "\
Place to override default theme semantic colors.

Semantic colors give meaning-based names (like `zenburn-comment'
or `zenburn-error') to entries in the positional palette.  Values
may be either a hex string or the symbol of a palette entry (for
example, `zenburn-yellow').  See `zenburn-default-semantic-colors-alist'
for the list of semantic names that ship with the theme.")
(custom-autoload 'zenburn-override-semantic-colors-alist "zenburn-theme" t)
(and load-file-name (boundp 'custom-theme-load-path) (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "zenburn-theme" '("zenburn"))

;;; End of scraped data

(provide 'zenburn-theme-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; zenburn-theme-autoloads.el ends here
