;;; hide-lines-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from hide-lines.el

(autoload 'hide-lines "hide-lines" "\
Hide lines matching the specified regexp.
With prefix ARG of 4 (\\[universal-argument]) hide lines that do not match the
specified regexp.  With any other prefix arg, reveal all hidden lines.

(fn &optional ARG)" t)
(autoload 'hide-blocks "hide-lines" "\
Hide blocks of lines between matching regexps.
With prefix ARG of 4 (\\[universal-argument]) hide blocks that do not match the
specified regexps.  With any other prefix arg, reveal all hidden blocks.

(fn &optional ARG)" t)
(autoload 'hide-lines-not-matching "hide-lines" "\
Hide lines that don't match the regexp SEARCH-TEXT.

(fn SEARCH-TEXT)" t)
(autoload 'hide-lines-matching "hide-lines" "\
Hide lines matching the regexp SEARCH-TEXT.

(fn SEARCH-TEXT)" t)
(autoload 'hide-blocks-not-matching "hide-lines" "\
Hide text that is not between lines matching START-TEXT and END-TEXT.

(fn START-TEXT END-TEXT)" t)
(autoload 'hide-blocks-matching "hide-lines" "\
Hide text that is between lines matching START-TEXT and END-TEXT.

(fn START-TEXT END-TEXT)" t)
(autoload 'hide-lines-show-all "hide-lines" "\
Unhide all hidden areas." t)
(register-definition-prefixes "hide-lines" '("hide-lines-"))

;;; End of scraped data

(provide 'hide-lines-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; hide-lines-autoloads.el ends here
