;;; cl-format-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from cl-format.el

(autoload 'cl-format "cl-format" "\
Format FMT using ARGS and print it to STREAM.

The full documentation not available until this function is
loaded.

(fn STREAM FMT &rest ARGS)")
(autoload 'cl-formatter "cl-format" "\
Compile FMT into a function.

This macro parses and compiles FMT into a function, which may be
passed as format argument to `cl-format'.

(fn FMT)" nil t)
(autoload 'cl-error "cl-format" "\
Like `error', but use CL format strings.

(fn FMT &rest ARGS)")
(autoload 'cl-message "cl-format" "\
Like `error', but use CL format strings.

(fn FMT &rest ARGS)")
(autoload 'cl-format-font-lock-mode "cl-format" "\
Adds font-lock support for cl format strings.

This is a minor mode.  If called interactively, toggle the
`Cl-Format-Font-Lock mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable
the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `cl-format-font-lock-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "cl-format" '("cl-format-"))


;;; Generated autoloads from cl-format-builtins.el

(register-definition-prefixes "cl-format-builtins" '("?$" "?%" "?&" "?*" "?/" "?<" "??" "?\\[" "?^" "?_" "?a" "?b" "?c" "?d" "?e" "?f" "?g" "?i" "?o" "?p" "?r" "?s" "?t" "?w" "?x" "?{" "?~" "cl-format-" "single-key-description-forthcoming"))


;;; Generated autoloads from cl-format-def.el

(register-definition-prefixes "cl-format-def" '("cl-" "define-cl-format-directive"))


;;; Generated autoloads from clisp-format.el

(register-definition-prefixes "clisp-format" '("clisp-"))

;;; End of scraped data

(provide 'cl-format-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; cl-format-autoloads.el ends here
