;;; backline-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from backline.el

(autoload 'backline-update "backline" "\
For collapsed sections extend their headers' appearance to the window edge.
Do nothing if `outline-minor-mode' isn't enable in the current buffer.

(fn FROM TO FLAG)")
(register-definition-prefixes "backline" '("backline--end-of-subtree"))

;;; End of scraped data

(provide 'backline-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; backline-autoloads.el ends here
