#!/usr/bin/env bash

mkdir -p _no-commit_/_analysis

find dev src -name "*.clj" \
    | xargs lein with-profile +clj-usage-graph \
            run -m com.gfredericks.clj-usage-graph/var-graph \
    | dot -Tpng -o _no-commit_/_analysis/gfredericks-var-graph.png
