#!/usr/bin/env bash

mkdir -p _analysis

lein nomis-ns-graph \
     :platform clj \
     :filename _analysis/nomis-deps-graph-global-clj-show-non-project-deps \
     :exclusions dev \
     :show-non-project-deps
