#!/usr/bin/env bash

mkdir -p _no-commit_/_analysis

lein-2-7-1 vizdeps \
           --vertical \
           --no-view \
           --output-file _no-commit_/_analysis/vizdeps-pruned.png \
           --prune
