#!/bin/bash

# Copied from https://akrabat.com/keyboard-control-of-macos-notification-alerts/

osascript -e 'tell application "System Events"
    tell process "NotificationCenter"
        click button 1 of window 1
    end tell
end tell'
