#!/usr/bin/env bash

mkdir -p _no-commit_/_analysis

lein nomis-ns-graph \
     :platform cljs \
     :filename _no-commit_/_analysis/nomis-deps-graph-global-cljs-show-non-project-deps \
     :exclusions dev \
     :show-non-project-deps
