;;; edn-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from edn.el

(autoload 'edn-time-to-inst "edn" "\
Turn a `time-date' TIME into our internal representation of an inst.

(fn TIME)")
(autoload 'edn-inst-to-time "edn" "\
Turn an `edn-inst', INST, into a TIME from `time-date'.

(fn INST)")
(autoload 'edn-string-to-uuid "edn" "\
Create an `edn-uuid' from a string, S, containing a uuid.

(fn S)")
(autoload 'edn-uuid-to-string "edn" "\
Turn our internal representation of a UUID into a string.

(fn UUID)")
(autoload 'edn-read "edn" "\
Read one edn value from SOURCE.

SOURCE is either a string of edn data or nil.  If no source is
given the next edn value will be read from POINT in the current
buffer.

You can use `edn-add-reader' to add your own readers for unknown
tags.

(fn &optional SOURCE)")
(autoload 'edn-list-to-set "edn" "\
Turn a list into `edn''s internal set representation.

If COMPARE-FN is provided this function is used to uniquify the
list.  Otherwise it's expected that l is without duplicates.

(fn L &optional COMPARE-FN)")
(autoload 'edn-set-to-list "edn" "\
Turn `edn''s internal set representation into a list.

(fn S)")
(autoload 'edn-add-reader "edn" "\
Add a READER function for TAG.

TAG is either a string, symbol or keyword. e.g. :my/type

(fn TAG READER)")
(autoload 'edn-add-writer "edn" "\
Add a WRITER function for types satisfying PRED.

(fn PRED WRITER)")
(autoload 'edn-remove-reader "edn" "\
Remove a previously registered handler for TAG.

(fn TAG)")
(autoload 'edn-remove-writer "edn" "\
The remove the writer WRITER.

(fn WRITER)")
(autoload 'edn-print-string "edn" "\
Serialize the lisp form DATUM into edn.

You can use `edn-add-writer' to add writers capable of writing
your own tagged data.

(fn DATUM)")
(register-definition-prefixes "edn" '("edn--" "hash-table-"))

;;; End of scraped data

(provide 'edn-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; edn-autoloads.el ends here
