;;; eca-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from eca.el

(autoload 'eca-debug-nrepl-connect "eca" "\
Connect in eca nrepl port for development." t)
(autoload 'eca "eca" "\
Start or switch to a eca session.
When ARG is current prefix, ask for workspace roots to use.

(fn &optional ARG)" t)
(autoload 'eca-stop "eca" "\
Stop eca if running." t)
(autoload 'eca-restart "eca" "\
Restart eca, if not running just start." t)
(autoload 'eca-workspaces "eca" "\
Display all running ECA sessions and their chats in a tree view." t)
(autoload 'eca-open-global-config "eca" "\
Open global ECA config file.
If the file does not exist, create the directory if needed and open a new
buffer visiting that path with `{}` pre-filled." t)
(register-definition-prefixes "eca" '("eca-"))


;;; Generated autoloads from eca-api.el

(register-definition-prefixes "eca-api" '("eca-"))


;;; Generated autoloads from eca-chat.el

(autoload 'eca-chat-clear "eca-chat" "\
Clear the eca chat." t)
(autoload 'eca-chat-select-model "eca-chat" "\
Select which model to use in the chat from what server supports." t)
(autoload 'eca-chat-select-agent "eca-chat" "\
Select which chat agent to use from what server supports." t)
(autoload 'eca-chat-cycle-agent "eca-chat" "\
Cycle between existing chat agents to use." t)
(autoload 'eca-chat-tool-call-accept-all "eca-chat" "\
Accept all pending approval tool call in chat." t)
(autoload 'eca-chat-tool-call-accept-all-and-remember "eca-chat" "\
Accept all pending approval tool call in chat and remember for session." t)
(autoload 'eca-chat-tool-call-accept-next "eca-chat" "\
Search the next pending approval tool call in the buffer and approve it, starting from the beginning of the buffer." t)
(autoload 'eca-chat-tool-call-reject-next "eca-chat" "\
Search the next pending approval tool call in the buffer and reject it, starting from the beginning of the buffer." t)
(autoload 'eca-chat-reset "eca-chat" "\
Kill current chat (asking to keep or not history) and start a new." t)
(autoload 'eca-chat-go-to-prev-user-message "eca-chat" "\
Go to the previous user message from point." t)
(autoload 'eca-chat-go-to-next-user-message "eca-chat" "\
Go to the next user message from point.
If there is no next user message, go to the chat prompt line." t)
(autoload 'eca-chat-go-to-prev-expandable-block "eca-chat" "\
Go to the previous expandable block from point." t)
(autoload 'eca-chat-go-to-next-expandable-block "eca-chat" "\
Go to the next expandable block from point." t)
(autoload 'eca-chat-toggle-expandable-block "eca-chat" "\
Toggle current expandable block at point.
Just open if FORCE-OPEN? is non-nil.

(fn &optional FORCE-OPEN?)" t)
(autoload 'eca-chat-expand-all-blocks "eca-chat" "\
Expand all expandable blocks in current chat." t)
(autoload 'eca-chat-collapse-all-blocks "eca-chat" "\
Collapse all expandable blocks in current chat." t)
(autoload 'eca-chat-add-context-to-system-prompt "eca-chat" "\
Add context to system prompt in chat in a DWIM manner.

- If a region selected, add file with lines range selected.
- If in Dired, add the marked files/dirs or current file/dir at point.
- If in Treemacs, add selected file/dir.
- Else add current file." t)
(autoload 'eca-chat-add-context-to-user-prompt "eca-chat" "\
Add context to user prompt in chat in a DWIM manner.

- If a region selected, add file with lines range selected.
- If in Dired, add the marked files/dirs or current file/dir at point.
- If in Treemacs, add selected file/dir.
- Else add current file." t)
(autoload 'eca-chat-add-filepath-to-user-prompt "eca-chat" "\
Add filepath to user prompt in chat in a DWIM manner.

- If a region selected, add filepath with lines range selected.
- If in Dired, add the marked files/dirs / current file/dir paths at point.
- If in Treemacs, add selected file/dir path.
- Else add current filepath." t)
(autoload 'eca-chat-drop-context-from-system-prompt "eca-chat" "\
Drop context from system prompt in chat if found.
if ARG is current prefix, ask for file, otherwise drop current file.

(fn &optional ARG)" t)
(autoload 'eca-chat-stop-prompt "eca-chat" "\
Stop chat prompt." t)
(autoload 'eca-chat-send-prompt "eca-chat" "\
Send PROMPT to current chat session.

(fn PROMPT)" t)
(autoload 'eca-chat-send-prompt-at-chat "eca-chat" "\
Send the prompt in chat if not empty." t)
(autoload 'eca-chat-toggle-window "eca-chat" "\
Toggle presenting ECA chat window." t)
(autoload 'eca-chat-select "eca-chat" "\
Select a chat." t)
(autoload 'eca-chat-rename "eca-chat" "\
Rename last visited chat to a custom NEW-NAME." t)
(autoload 'eca-chat-new "eca-chat" "\
Start a new ECA chat for same session." t)
(autoload 'eca-chat-talk "eca-chat" "\
Talk to the assistent by recording audio and transcribing it." t)
(autoload 'eca-chat-timeline "eca-chat" "\
Navigate to a user message via completion." t)
(autoload 'eca-chat-clear-prompt "eca-chat" "\
Clear the prompt input field in chat." t)
(autoload 'eca-chat-repeat-prompt "eca-chat" "\
Select a previous message and insert its text into the prompt." t)
(autoload 'eca-chat-save-to-file "eca-chat" "\
Export the current chat to a FILE.

(fn &optional FILE)" t)
(register-definition-prefixes "eca-chat" '("eca-chat-"))


;;; Generated autoloads from eca-completion.el

(autoload 'eca-completion-mode "eca-completion" "\
Minor mode for ECA completions.

This is a minor mode.  If called interactively, toggle the
`Eca-Completion mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `eca-completion-mode'.

The mode's hook is called both when the mode is enabled and when it
is disabled.

(fn &optional ARG)" t)
(autoload 'eca-complete "eca-completion" "\
Complete at the current point." t)
(register-definition-prefixes "eca-completion" '("eca-completion-"))


;;; Generated autoloads from eca-diff.el

(register-definition-prefixes "eca-diff" '("eca-diff-"))


;;; Generated autoloads from eca-editor.el

(register-definition-prefixes "eca-editor" '("eca-editor-"))


;;; Generated autoloads from eca-mcp.el

(autoload 'eca-mcp-details "eca-mcp" "\
List MCP servers with their status and options." t)
(register-definition-prefixes "eca-mcp" '("eca-mcp-"))


;;; Generated autoloads from eca-process.el

(autoload 'eca-show-stderr "eca-process" "\
Open the eca process stderr buffer if running." t)
(autoload 'eca-install-server "eca-process" "\
Force download the latest eca server." t)
(autoload 'eca-uninstall-server "eca-process" "\
Remove downloaded eca server if present." t)
(register-definition-prefixes "eca-process" '("eca-"))


;;; Generated autoloads from eca-rewrite.el

(autoload 'eca-rewrite "eca-rewrite" "\
Rewrite a text with a new LLM generated one.
- If on an existing rewrite overlay, re-iterate
- Else if region active, rewrite that region
- Else try to detect defun/paragraph boundaries

PROMPT is the instructions prompt for the LLM.

(fn &optional PROMPT)" t)
(autoload 'eca-rewrite-reject "eca-rewrite" "\
Reject rewrite overlay at point." t)
(autoload 'eca-rewrite-accept "eca-rewrite" "\
Accept rewrite overlay at point." t)
(autoload 'eca-rewrite-retry "eca-rewrite" "\
Retry rewrite overlay at point." t)
(autoload 'eca-rewrite-diff "eca-rewrite" "\
Apply diff between original text and rewrite overlay at point." t)
(autoload 'eca-rewrite-merge "eca-rewrite" "\
Merge between original text and rewrite overlay OV." t)
(register-definition-prefixes "eca-rewrite" '("eca-rewrite-"))


;;; Generated autoloads from eca-util.el

(register-definition-prefixes "eca-util" '("eca-"))

;;; End of scraped data

(provide 'eca-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; eca-autoloads.el ends here
