;;; tldr-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from tldr.el

(autoload 'tldr-update-docs "tldr" "\
Get or update the TLDR docs from source." t)
(autoload 'tldr "tldr" "\
Lookup TLDR docs.

(fn &optional CMD)" t)
(autoload 'helm-tldr "tldr" "\
Helm interface for `tldr'." t)
(register-definition-prefixes "tldr" '("tldr-"))

;;; End of scraped data

(provide 'tldr-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; tldr-autoloads.el ends here
