;;; applescript-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from applescript-mode.el

(autoload 'applescript-mode "applescript-mode" "\
Major mode for editing AppleScript files." t)
(add-to-list 'auto-mode-alist '("\\.\\(applescript\\|scpt\\)\\'" . applescript-mode))
(add-to-list 'interpreter-mode-alist '("osascript" . applescript-mode))
(register-definition-prefixes "applescript-mode" '("applescript-" "as-"))

;;; End of scraped data

(provide 'applescript-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; applescript-mode-autoloads.el ends here
